%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%player_ID(Name, objectIndex(Index), Value).
%player_Type(Name, objectIndex(Index), Value).
%player_Name(Name, objectIndex(Index), Value).
%player_X(Name, objectIndex(Index), Value).
%player_Y(Name, objectIndex(Index), Value).
%player_Pos_x(Name, objectIndex(Index), Value).
%player_Pos_y(Name, objectIndex(Index), Value).
%player_SelectedInteractableType(Name, objectIndex(Index), Value).
%player_HasSpace(Name, objectIndex(Index), Value).
%player_HasAny(Name, objectIndex(Index), Value).
%player_FirstKitchenObject_Name(Name, objectIndex(Index), Value).
%player_FirstKitchenObject_ID(Name, objectIndex(Index), Value).
%player_ContainerID(Name, objectIndex(Index), Value).
%player_KitchenObject_Name(Name, objectIndex(Index), Index1,Value).
%player_KitchenObject_ID(Name, objectIndex(Index), Index1,Value).
%player_KitchenObject_ContainerID(Name, objectIndex(Index), Index1,Value).
%player_Count(Name, objectIndex(Index), Value).
%player_SizeLimit(Name, objectIndex(Index), Value).
%player_KOContainerSensorData_ContainerID(Name, objectIndex(Index), Value).
%player_PlayerSensorData_SelectedInteractableID000(Name, objectIndex(Index), Value).
%player_HasSelectedInteractable(Name, objectIndex(Index), Value).
%counterSensor_ID(Name, objectIndex(Index), Value).
%counterSensor_Type(Name, objectIndex(Index), Value).
%counterSensor_Name(Name, objectIndex(Index), Value).
%counterSensor_X(Name, objectIndex(Index), Value).
%counterSensor_Y(Name, objectIndex(Index), Value).
%counterSensor_ContainerID(Name, objectIndex(Index), Value).
%counterSensor_SizeLimit(Name, objectIndex(Index), Value).
%counterSensor_Count(Name, objectIndex(Index), Value).
%counterSensor_KitchenObject_Name(Name, objectIndex(Index), Index1,Value).
%counterSensor_KitchenObject_ID(Name, objectIndex(Index), Index1,Value).
%counterSensor_KitchenObject_ContainerID(Name, objectIndex(Index), Index1,Value).
%counterSensor_FirstKitchenObject_Name(Name, objectIndex(Index), Value).
%counterSensor_FirstKitchenObject_ID(Name, objectIndex(Index), Value).
%counterSensor_FirstKitchenObject_ContainerID(Name, objectIndex(Index), Value).
%counterSensor_HasAny(Name, objectIndex(Index), Value).
%counterSensor_HasSpace(Name, objectIndex(Index), Value).
%counterSensor_ID(Name, objectIndex(Index), Value).
%counterSensor_Type(Name, objectIndex(Index), Value).
%counterSensor_Name(Name, objectIndex(Index), Value).
%counterSensor_X(Name, objectIndex(Index), Value).
%counterSensor_Y(Name, objectIndex(Index), Value).
%counterSensor_KitchenObject_Name(Name, objectIndex(Index), Index1,Value).
%counterSensor_KitchenObject_ID(Name, objectIndex(Index), Index1,Value).
%counterSensor_KitchenObject_ContainerID(Name, objectIndex(Index), Index1,Value).
%counterSensor_FirstKitchenObject_Name(Name, objectIndex(Index), Value).
%counterSensor_FirstKitchenObject_ID(Name, objectIndex(Index), Value).
%counterSensor_FirstKitchenObject_ContainerID(Name, objectIndex(Index), Value).
%counterSensor_HasAny(Name, objectIndex(Index), Value).
%counterSensor_HasSpace(Name, objectIndex(Index), Value).
%cuttingCounterSensor_ContainerID(Name, objectIndex(Index), Value).
%cuttingCounterSensor_SizeLimit(Name, objectIndex(Index), Value).
%cuttingCounterSensor_KOContainerSensorData_Count(Name, objectIndex(Index), Value).
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
