%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%clearCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%clearCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasSpace(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasAny(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(name(Value)))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(iD(Value)))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(containerID(Value)))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(name(Value))))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(iD(Value))))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(containerID(Value))))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(count(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(sizeLimit(Value))).
%clearCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(containerID(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%containerCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasSpace(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasAny(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(name(Value)))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(iD(Value)))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(containerID(Value)))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(name(Value))))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(iD(Value))))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(containerID(Value))))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(count(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(sizeLimit(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(containerID(Value))).
%containerCounterSensors(counterSensors,objectIndex(Index),containerCounterSensorData(kOType(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasSpace(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasAny(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(name(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(iD(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(containerID(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(name(Value))))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(iD(Value))))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(containerID(Value))))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(count(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(sizeLimit(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(containerID(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(isBurning(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(timeRemainingToCook(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(canCook(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(hasAny(Value))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(currentCookingRecipe(name(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(currentCookingRecipe(inputKOName(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(currentCookingRecipe(outputKOName(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(currentCookingRecipe(timeToCook(Value)))).
%stoveCounterSensors(counterSensors,objectIndex(Index),stoveCounterSensorData(currentCookingRecipe(isBurningRecipe(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasSpace(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasAny(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(name(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(iD(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(containerID(Value)))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(name(Value))))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(iD(Value))))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(containerID(Value))))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(count(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(sizeLimit(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(containerID(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),platesCounterSensorData(platesLimit(Value))).
%platesCounterSensors(counterSensors,objectIndex(Index),platesCounterSensorData(platesCount(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasSpace(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(hasAny(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(name(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(iD(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(firstKitchenObject(containerID(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(name(Value))))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(iD(Value))))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(kitchenObjects(Index1,kitchenObject(containerID(Value))))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(count(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(sizeLimit(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),kOContainerSensorData(containerID(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(hasAny(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(canCut(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(timeRemainingToCut(Value))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(currentCuttingRecipe(name(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(currentCuttingRecipe(inputKOName(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(currentCuttingRecipe(outputKOName(Value)))).
%cuttingCounterSensors(counterSensors,objectIndex(Index),cuttingCounterSensorData(currentCuttingRecipe(timeToCut(Value)))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(completeRecipes(Index1,completeRecipe(name(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(completeRecipes(Index1,completeRecipe(ingredientsNames(Index2,Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(completeRecipes(Index1,completeRecipe(value(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cookingRecipes(Index1,cookingRecipe(name(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cookingRecipes(Index1,cookingRecipe(inputKOName(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cookingRecipes(Index1,cookingRecipe(outputKOName(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cookingRecipes(Index1,cookingRecipe(timeToCook(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cookingRecipes(Index1,cookingRecipe(isBurningRecipe(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cuttingRecipes(Index1,cuttingRecipe(name(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cuttingRecipes(Index1,cuttingRecipe(inputKOName(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cuttingRecipes(Index1,cuttingRecipe(outputKOName(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(cuttingRecipes(Index1,cuttingRecipe(timeToCut(Value))))).
%constantSensor(constantSensors,objectIndex(Index),constantsSensorData(kitchenObjectsNames(Index1,Value))).
%trashCounterSensors(counterSensors,objectIndex(Index),baseSensorData(iD(Value))).
%trashCounterSensors(counterSensors,objectIndex(Index),baseSensorData(type(Value))).
%trashCounterSensors(counterSensors,objectIndex(Index),baseSensorData(name(Value))).
%trashCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(x(Value)))).
%trashCounterSensors(counterSensors,objectIndex(Index),gridPositionSensorData(pos(y(Value)))).
