%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%s_Player_ID(playerSensors,objectIndex(Index),Value).
%s_Player_Type(playerSensors,objectIndex(Index),Value).
%s_Player_Name(playerSensors,objectIndex(Index),Value).
%s_Player_HasSelectedInteractable(playerSensors,objectIndex(Index),Value).
%s_Player_SelectedInteractableType(playerSensors,objectIndex(Index),Value).
%s_Player_SelectedInteractableID(playerSensors,objectIndex(Index),Value).
%s_Player_ContainerID(playerSensors,objectIndex(Index),Value).
%s_Player_SizeLimit(playerSensors,objectIndex(Index),Value).
%s_Player_Count(playerSensors,objectIndex(Index),Value).
%s_Player_KitchenObject_Name(playerSensors,objectIndex(Index),Index1,Value).
%s_Player_KitchenObject_ID(playerSensors,objectIndex(Index),Index1,Value).
%s_Player_KitchenObject_ContainerID(playerSensors,objectIndex(Index),Index1,Value).
%s_Player_FirstKitchenObject_Name(playerSensors,objectIndex(Index),Value).
%s_Player_FirstKitchenObject_ID(playerSensors,objectIndex(Index),Value).
%s_Player_FirstKitchenObject_ContainerID(playerSensors,objectIndex(Index),Value).
%s_Player_HasSpace(playerSensors,objectIndex(Index),Value).
%s_Player_HasAny(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_ID(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_HasRecipe(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_RecipeName(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_HasPlate(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_PlateForRecipeID(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_HasMissingIngredients(playerSensors,objectIndex(Index),Value).
%s_PlayerBot_MissingIngredientsNames(playerSensors,objectIndex(Index),Index1,Value).
%s_PlayerBot_HasInvalidIngredients(playerSensors,objectIndex(Index),Value).
%s_Plate_ID(plateSensor,objectIndex(Index),Value).
%s_Plate_Type(plateSensor,objectIndex(Index),Value).
%s_Plate_Name(plateSensor,objectIndex(Index),Value).
%s_Plate_ContainerID(plateSensor,objectIndex(Index),Value).
%s_Plate_Count(plateSensor,objectIndex(Index),Value).
%s_Plate_KitchenObject_Name(plateSensor,objectIndex(Index),Index1,Value).
%s_Plate_KitchenObject_ID(plateSensor,objectIndex(Index),Index1,Value).
%s_Plate_KitchenObject_ContainerID(plateSensor,objectIndex(Index),Index1,Value).
%s_Plate_FirstKitchenObject_Name(plateSensor,objectIndex(Index),Value).
%s_Plate_FirstKitchenObject_ID(plateSensor,objectIndex(Index),Value).
%s_Plate_FirstKitchenObject_ContainerID(plateSensor,objectIndex(Index),Value).
%s_Plate_HasSpace(plateSensor,objectIndex(Index),Value).
%s_Plate_HasAny(plateSensor,objectIndex(Index),Value).
%s_Plate_SizeLimit(plateSensor,objectIndex(Index),Value).
%s_Plate_OwnerContainerID(plateSensor,objectIndex(Index),Value).
%s_Plate_IsInContainer(plateSensor,objectIndex(Index),Value).
%s_CuttingCounter_ID(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_HasAny(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CanCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_TimeRemainingToCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_Name(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_InputKOName(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_OutputKOName(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_TimeToCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_PlatesCounter_ID(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesLimit(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesCount(counterSensor,objectIndex(Index),Value).
%s_Delivery_WaitingRecipesNames(deliverySensor,objectIndex(Index),Index1,Value).
%s_ContainerCounter_ID(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_KOType(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_ID(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_HasAny(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CanCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_TimeRemainingToCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_IsBurning(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_Name(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_InputKOName(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_OutputKOName(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_TimeToCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_IsBurningRecipe(counterSensor,objectIndex(Index),Value).
%s_Counter_ID(counterSensor,objectIndex(Index),Value).
%s_Counter_Type(counterSensor,objectIndex(Index),Value).
%s_Counter_Name(counterSensor,objectIndex(Index),Value).
%s_Counter_X(counterSensor,objectIndex(Index),Value).
%s_Counter_Y(counterSensor,objectIndex(Index),Value).
%s_Counter_ContainerID(counterSensor,objectIndex(Index),Value).
%s_Counter_SizeLimit(counterSensor,objectIndex(Index),Value).
%s_Counter_Count(counterSensor,objectIndex(Index),Value).
%s_Counter_KitchenObject_Name(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_KitchenObject_ID(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_KitchenObject_ContainerID(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_FirstKitchenObject_Name(counterSensor,objectIndex(Index),Value).
%s_Counter_FirstKitchenObject_ID(counterSensor,objectIndex(Index),Value).
%s_Counter_FirstKitchenObject_ContainerID(counterSensor,objectIndex(Index),Value).
%s_Counter_HasAny(counterSensor,objectIndex(Index),Value).
%s_Counter_HasSpace(counterSensor,objectIndex(Index),Value).
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
