%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%s_ContainerCounter_KOType(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_ID(counterSensor,objectIndex(Index),Value).
%s_CuttingCounter_HasAny(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CanCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_TimeRemainingToCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_Name(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_ID(cuttingCounterSensor,objectIndex(Index),Value).
%s_StoveCounter_HasAny(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CanCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_TimeRemainingToCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_IsBurning(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_Name(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_ID(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_ID(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesLimit(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesCount(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_TimeToNextPlate(counterSensor,objectIndex(Index),Value).
%s_PlayerBot_HasRecipe(player,objectIndex(Index),Value).
%s_PlayerBot_RecipeName(player,objectIndex(Index),Value).
%s_PlayerBot_HasPlate(player,objectIndex(Index),Value).
%s_PlayerBot_PlateForRecipeID(player,objectIndex(Index),Value).
%s_PlayerBot_HasMissingIngredients(player,objectIndex(Index),Value).
%s_PlayerBot_MissingIngredientsNames(player,objectIndex(Index),Index1,Value).
%s_PlayerBot_HasInvalidIngredients(player,objectIndex(Index),Value).
%s_PlayerBot_PlayerBotSensorData_CurrentRecipeRequestASP_ID(player,objectIndex(Index),Value).
%s_Delivery_RecipeRequest_ID(deliverySensor,objectIndex(Index),Index1,Value).
%s_Delivery_RecipeRequest_TimeToComplete(deliverySensor,objectIndex(Index),Index1,Value).
%s_Delivery_RecipeRequest_RemainingTimeToComplete(deliverySensor,objectIndex(Index),Index1,Value).
%s_Delivery_RecipeRequest_Name(deliverySensor,objectIndex(Index),Index1,Value).
%s_Delivery_RecipeRequest_IngredientsNames(deliverySensor,objectIndex(Index),Index1,Index2,Value).
%s_Delivery_RecipeRequest_Value(deliverySensor,objectIndex(Index),Index1,Value).
%s_Const_KitchenObjectsNames0(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_Name(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_InputKOName(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_OutputKOName(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_TimeToCut(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_IsBurningRecipe(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_TimeToCook(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_OutputKOName(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_InputKOName(constantsSensor,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_Name(constantsSensor,objectIndex(Index),Index1,Value).
%s_Plate_ID(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_ContainerID(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_SizeLimit(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_Count(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_HasSpace(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_HasAny(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_KitchenObjectASP_Name(kitchenObjectSensor,objectIndex(Index),Index1,Value).
%s_Plate_KitchenObjectASP_ID(kitchenObjectSensor,objectIndex(Index),Index1,Value).
%s_Plate_KitchenObjectASP_ContainerID(kitchenObjectSensor,objectIndex(Index),Index1,Value).
%s_Plate_FirstKitchenObject_Name(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_FirstKitchenObject_ID(kitchenObjectSensor,objectIndex(Index),Value).
%s_Plate_FirstKitchenObject_ContainerID(kitchenObjectSensor,objectIndex(Index),Value).
%s_Counter_ID(counterSensor,objectIndex(Index),Value).
%s_Counter_Type(counterSensor,objectIndex(Index),Value).
%s_Counter_Name(counterSensor,objectIndex(Index),Value).
%s_Counter_ContainerID(counterSensor,objectIndex(Index),Value).
%s_Counter_SizeLimit(counterSensor,objectIndex(Index),Value).
%s_Counter_Count(counterSensor,objectIndex(Index),Value).
%s_Counter_FirstKitchenObject_Name(counterSensor,objectIndex(Index),Value).
%s_Counter_FirstKitchenObject_ID(counterSensor,objectIndex(Index),Value).
%s_Counter_FirstKitchenObject_ContainerID(counterSensor,objectIndex(Index),Value).
%s_Counter_HasAny(counterSensor,objectIndex(Index),Value).
%s_Counter_HasSpace(counterSensor,objectIndex(Index),Value).
%s_Counter_KitchenObject_Name(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_KitchenObject_ID(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_KitchenObject_ContainerID(counterSensor,objectIndex(Index),Index1,Value).
%s_Counter_X(counterSensor,objectIndex(Index),Value).
%s_Counter_Y(counterSensor,objectIndex(Index),Value).
%s_KO_ID(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_Type(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_Name(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_OwnerContainerID(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_HasPlayer(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_PlayerID(kitchenObjectSensor,objectIndex(Index),Value).
%s_KO_HasOwnerContainer(kitchenObjectSensor,objectIndex(Index),Value).
%s_Player_ID(player,objectIndex(Index),Value).
%s_Player_Type(player,objectIndex(Index),Value).
%s_Player_Name(player,objectIndex(Index),Value).
%s_Player_ContainerID(player,objectIndex(Index),Value).
%s_Player_SizeLimit(player,objectIndex(Index),Value).
%s_Player_Count(player,objectIndex(Index),Value).
%s_Player_ContainerID(player,objectIndex(Index),Value).
%s_Player_SizeLimit(player,objectIndex(Index),Value).
%s_Player_Count(player,objectIndex(Index),Value).
%s_Player_KitchenObject_Name(player,objectIndex(Index),Index1,Value).
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
