%For runtime instantiated GameObject, only the prefab mapping is provided. Use that one substituting the gameobject name accordingly.
 %Sensors.
%s_Player_ID(player,objectIndex(Index),Value).
%s_Player_Type(player,objectIndex(Index),Value).
%s_Player_Name(player,objectIndex(Index),Value).
%s_Player_HasSelectedInteractable(player,objectIndex(Index),Value).
%s_Player_SelectedInteractableType(player,objectIndex(Index),Value).
%s_Player_SelectedInteractableID(player,objectIndex(Index),Value).
%s_Player_HasRecipe(player,objectIndex(Index),Value).
%s_Player_RecipeName(player,objectIndex(Index),Value).
%s_Player_HasPlate(player,objectIndex(Index),Value).
%s_Player_PlateForRecipeID(player,objectIndex(Index),Value).
%s_Player_HasMissingIngredients(player,objectIndex(Index),Value).
%s_Player_MissingIngredientsNames(player,objectIndex(Index),Index1,Value).
%s_Player_HasInvalidIngredients(player,objectIndex(Index),Value).
%s_Player_X(player,objectIndex(Index),Value).
%s_Player_Y(player,objectIndex(Index),Value).
%s_Player_Container_Count(player,objectIndex(Index),Value).
%s_Player_HasSpace(player,objectIndex(Index),Value).
%s_Player_HasAny(player,objectIndex(Index),Value).
%s_Player_KitchenObject_Name(player,objectIndex(Index),Index1,Value).
%s_Player_KitchenObject_ID(player,objectIndex(Index),Index1,Value).
%s_Player_KitchenObject_ContainerID(player,objectIndex(Index),Index1,Value).
%s_Player_FirstKitchenObject_Name(player,objectIndex(Index),Value).
%s_Player_FirstKitchenObject_ID(player,objectIndex(Index),Value).
%s_Player_FirstKitchenObject_ContainerID(player,objectIndex(Index),Value).
%s_Player_Container_SizeLimit(player,objectIndex(Index),Value).
%s_Player_ContainerID(player,objectIndex(Index),Value).
%s_Const_KitchenObjectsNames(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CompleteRecipe_Name(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CompleteRecipe_IngredientNames(constantSensors,objectIndex(Index),Index1,Index2,Value).
%s_Const_CompleteRecipe_Value(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_Name(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_OutputKOName(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_TimeToCook(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_IsBurningRecipe(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_Name(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_InputKOName(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_OutputKOName(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CuttingRecipe_TimeToCut(constantSensors,objectIndex(Index),Index1,Value).
%s_Const_CookingRecipe_InputKOName(constantSensors,objectIndex(Index),Index1,Value).
%s_CuttingCounter_ID(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_HasAny(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CanCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_TimeRemainingToCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_Name(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_InputKOName(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_OutputKOName(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_CurrentCuttingRecipe_TimeToCut(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_Type(cuttingCounterSensor,objectIndex(Index),Value).
%s_CuttingCounter_Name(cuttingCounterSensor,objectIndex(Index),Value).
%s_PlatesCounter_ID(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_Type(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_Name(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesLimit(counterSensor,objectIndex(Index),Value).
%s_PlatesCounter_PlatesCount(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_ID(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_Type(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_Name(counterSensor,objectIndex(Index),Value).
%s_ContainerCounter_KOType(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_ID(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_Type(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_Name(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_HasAny(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CanCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_TimeRemainingToCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_IsBurning(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_Name(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_InputKOName(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_OutputKOName(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_TimeToCook(counterSensor,objectIndex(Index),Value).
%s_StoveCounter_CurrentCookingRecipe_IsBurningRecipe(counterSensor,objectIndex(Index),Value).
%For ASP programs:
% Predicates for Action invokation.
% applyAction(OrderOfExecution,ActionClassName).
% actionArgument(ActionOrder,ArgumentName, ArgumentValue).
